# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f5ad20ebb8e26554d0fbf2615385f6e429a7f196d763a00a33cd1203e7222c86c9739fa3aeac1de7b904f33c184cee7c418be59e2c6f63fa696306f3268558

test:
  secret_key_base: 7fc9c6d51c079bc7e3821157f3a65f53e2c8e9a717ab88cf13da47d8e430949dd78d49632e03885f292d238610ed1e9f2e015b92612d8b47196566ad8c2aeca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
